[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
# This runner will flash a mounted RP2040 in USB Bootloader mode:
runner = "picotool load --update --verify --execute -t elf"
# This runner will find a supported SWD debug probe and flash your RP2040 over SWD:
# runner = "probe-rs run --chip RP2040"
linker = "flip-link"
rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "no-vectorize-loops",
]

[env]
DEFMT_LOG = "debug"
